# Generated by Django 4.2.8 on 2023-12-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50, unique=True)),
                ('core_quantity', models.IntegerField()),
                ('cpu_speed', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Gpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50, unique=True)),
                ('memory_amount', models.IntegerField()),
                ('gpu_speed', models.FloatField()),
                ('memory_speed', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50, unique=True)),
                ('memory_type', models.CharField(choices=[('hdd', 'HDD'), ('ssd', 'SSD'), ('nvme', 'NVMe')], max_length=5)),
                ('slot_type', models.CharField(choices=[('pata', 'PATA'), ('sata', 'SATA'), ('pcie', 'PCIe'), ('m.2', 'M.2')], max_length=5)),
                ('memory_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50, unique=True)),
                ('chipset', models.CharField(max_length=20)),
                ('cpu_compatibility', models.CharField(choices=[('intel', 'Intel'), ('amd', 'AMD')], max_length=10)),
                ('integrated_gpu', models.BooleanField(default=False)),
                ('ram_slots', models.IntegerField()),
                ('usb_slots', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Psu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50, unique=True)),
                ('watt', models.IntegerField()),
                ('premium_quality', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50, unique=True)),
                ('memory_type', models.CharField(choices=[('ddr1', 'DDR1'), ('ddr2', 'DDR2'), ('ddr3', 'DDR3'), ('ddr4', 'DDR4'), ('ddr5', 'DDR5')], max_length=10)),
                ('memory_amount', models.IntegerField()),
                ('memory_speed', models.FloatField()),
            ],
        ),
    ]
