# Generated by Django 4.2.8 on 2023-12-21 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='core_quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='memory_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='memory',
            name='memory_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='ram_slots',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='usb_slots',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='psu',
            name='watt',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ram',
            name='memory_amount',
            field=models.PositiveIntegerField(),
        ),
    ]
