# Generated by Django 4.2.8 on 2023-12-21 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_alter_cpu_core_quantity_alter_gpu_memory_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='cpu_speed',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='gpu_speed',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='memory_speed',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='ram',
            name='memory_speed',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
