# Generated by Django 4.2.8 on 2023-12-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_cpu_cpu_socket_cpu_thread_quantity_alter_cpu_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpu',
            name='brand',
        ),
        migrations.AddField(
            model_name='gpu',
            name='gpu_brand',
            field=models.CharField(choices=[('nvidia', 'Nvidia'), ('ati', 'ATI')], default='nvidia', max_length=10),
        ),
        migrations.AddField(
            model_name='gpu',
            name='vga_brand',
            field=models.CharField(choices=[('nvidia', 'Nvidia'), ('ati', 'ATI'), ('asus', 'ASUS'), ('msi', 'MSI'), ('sapphire', 'SAPPHIRE'), ('evga', 'EVGA')], default='nvidia', max_length=10),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_socket',
            field=models.CharField(choices=[('lga_1150', 'LGA 1150'), ('lga_1151', 'LGA 1151'), ('lga_1200', 'LGA 1200'), ('lga_1700', 'LGA 1700'), ('lga_2011', 'LGA 2011'), ('lga_2011_v3', 'LGA 2011-v3'), ('lga_2066', 'LGA 2066'), ('lga_4677', 'LGA 4677'), ('fm2+', 'FM2+'), ('am4', 'AM4'), ('am5', 'AM5'), ('tr4', 'TR4'), ('trx4', 'TRX4'), ('strx4', 'sTRX4'), ('str5', 'sTR5')], max_length=12),
        ),
    ]
