# Generated by Django 4.2.8 on 2023-12-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_remove_gpu_brand_gpu_gpu_brand_gpu_vga_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ram',
            name='memory_kit',
            field=models.BooleanField(default=True),
        ),
    ]
