# Generated by Django 4.2.8 on 2023-12-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0007_ram_memory_kit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='brand',
            field=models.CharField(choices=[('Intel', 'Intel'), ('amd', 'AMD')], max_length=20),
        ),
        migrations.AlterField(
            model_name='memory',
            name='model',
            field=models.CharField(max_length=50),
        ),
    ]
