# Generated by Django 4.2.8 on 2023-12-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0008_alter_cpu_brand_alter_memory_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='cpu_socket',
            field=models.CharField(choices=[('LGA 775', 'LGA 775'), ('lga_1150', 'LGA 1150'), ('lga_1151', 'LGA 1151'), ('lga_1200', 'LGA 1200'), ('lga_1700', 'LGA 1700'), ('lga_2011', 'LGA 2011'), ('lga_2011_v3', 'LGA 2011-v3'), ('lga_2066', 'LGA 2066'), ('lga_4677', 'LGA 4677'), ('fm2+', 'FM2+'), ('am4', 'AM4'), ('am5', 'AM5'), ('tr4', 'TR4'), ('trx4', 'TRX4'), ('strx4', 'sTRX4'), ('str5', 'sTR5')], max_length=12),
        ),
    ]
