# Generated by Django 4.2.8 on 2023-12-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0009_memory_image_alter_motherboard_cpu_socket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='image',
            field=models.ImageField(null=True, upload_to='images/memory'),
        ),
    ]
