# Generated by Django 4.2.8 on 2023-12-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0006_remove_gpu_brand_gpu_gpu_brand_gpu_vga_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.ForeignKey(on_delete=models.SET(None), to='parts.cpu')),
                ('gpu', models.ForeignKey(on_delete=models.SET(None), to='parts.gpu')),
                ('mem', models.ForeignKey(on_delete=models.SET(None), to='parts.memory')),
                ('motherboard', models.ForeignKey(on_delete=models.SET(None), to='parts.motherboard')),
                ('psu', models.ForeignKey(on_delete=models.SET(None), to='parts.psu')),
                ('ram', models.ForeignKey(on_delete=models.SET(None), to='parts.ram')),
            ],
        ),
    ]
