# Generated by Django 4.2.8 on 2023-12-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('weight', models.FloatField()),
            ],
        ),
    ]
